project:
  type: book
  output-dir: docs

book:
  title: "BS3037: Virology"
  author: "Kevin Fo"
  date: "05/08/2023"
  chapters:
    - index.qmd
    - part: "**PART I: LECTURE NOTES**"
      chapters:
        - chapters/week1.qmd
        - chapters/week3.qmd
        - chapters/week3actual.qmd
        - chapters/week4.qmd
        - chapters/week5.qmd
        - chapters/week6.qmd
        - chapters/week11.qmd
        - chapters/week12.qmd
    - part: "**PART 2: TUTORIAL NOTES**"
      chapters:
        - chapters/week2.qmd
        - chapters/tut2.qmd
        - chapters/week3tut.qmd
        - chapters/week5tut.qmd
  sharing: [twitter, facebook]
  page-navigation: true
  repo-url: https://github.com/kevfo/BS3037_Notes/
  repo-actions: [edit, issue]
  reader-mode: true
  comments: 
    hypothesis: true

format:
  html:
    toc: true 
    theme:
      light: cosmo
      dark: darkly
      
editor: visual

