# Preface {.unnumbered}


*BS3037: Virology* is a 13-week module that is worth three **a**cademic **u**nits (i.e., **AUs**).  More information about this course will be shown in the following sections of this page.

## Course Objectives

BS3037 is a systematic approach to talk about viruses and their biology.  Although it is not a medical virology course, issues related to public health will be covered.

The following ideas will be examined throughout the course:

- How do viruses differ from microorganisms?
- How do viruses replicate?
- What are some current strategies to diagnose viruses and to prevent their spread?
- What is the relevance of a viral threat on a local and an international context?
- What are some clinical and economical implications of viral infections?

## Grading Criteria

BS3037 has three main grading components:

1.  Research project (30% of final grade)
    
    This is carried out in small groups of three to four students.
    
1.  A Mid Term Exam (10% of grade)
1.  Final Exam (60% of grade)


